version: '3.7'

services:
    postgres:
        image:   postgres:9.6
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - ${DOCKER_DIR}/postgres/config/data:/var/lib/postgresql/data
        ports:
            -   published: 5432
                target:    5432
        logging:
            options:
                max-size: 10m
                max-file: "3"
        restart: unless-stopped

    airflow:
        image:   puckel/docker-airflow:1.10.9
        environment:
            - EXECUTOR=${AIRFLOW_EXECUTOR}
        volumes:
            - ${DOCKER_DIR}/:/usr/local/airflow/
        ports:
            -   published: 8080
                target:    8080
        command: webserver
        logging:
            options:
                max-size: 10m
                max-file: "3"
        healthcheck:
            test: [ "CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]" ]
            interval: 30s
            timeout:  30s
            retries:  3
        depends_on:
            - postgres
        restart: unless-stopped